import { ref, computed } from 'vue'
import { defineStore } from 'pinia'
import type { Opportunity, OpportunityStage, Priority, ServiceType } from '@/types'

export const useOpportunitiesStore = defineStore('opportunities', () => {
  const opportunities = ref<Opportunity[]>([
    {
      id: 'OPP-001',
      opportunityNumber: 'OPP-2024-001',
      name: 'Server Infrastructure Upgrade - ABC Corp',
      description: 'Complete server infrastructure replacement including 10 enterprise servers, storage arrays, and network equipment',
      companyId: 'CUST-001',
      contactId: 'CNT-001',
      serviceType: 'Security Systems',
      stage: 'proposal',
      priority: 'high',
      estimatedValue: 450000,
      targetMargin: 20,
      estimatedCost: 360000,
      currency: 'SAR',
      winProbability: 70,
      requestDate: '2024-01-15',
      teamId: 'TEAM-001', // Sales Team got this lead
      createdByPersonId: 'MEM-001', // Ahmed Al-Salem from Sales Team
      quoteSalesPersonId: 'MEM-002', // Fatima Al-Otaibi - Sales
      quotePresalesPersonId: 'MEM-004', // Khalid Al-Mutairi - Pre-Sales
      salesExecutiveId: 'USR-001',
      presalesId: 'USR-003',
      createdAt: '2024-01-15T10:30:00Z',
      createdBy: 'USR-001',
      notes: 'High priority client, good relationship. Competing with 2 other vendors.',
      quoteDates: [
        {
          quoteId: 'QUO-001',
          sentDate: '2024-01-20T00:00:00Z',
          respondedDate: '2024-01-25T00:00:00Z'
        }
      ]
    },
    {
      id: 'OPP-002',
      opportunityNumber: 'OPP-2024-002',
      name: 'Network Security Implementation - XYZ Industries',
      description: 'Comprehensive network security solution including firewalls, IPS/IDS, and security monitoring',
      companyId: 'CUST-002',
      contactId: 'CNT-002',
      serviceType: 'Security Systems',
      stage: 'qualification',
      priority: 'medium',
      estimatedValue: 280000,
      targetMargin: 18,
      estimatedCost: 229600,
      currency: 'SAR',
      winProbability: 50,
      requestDate: '2024-01-18',
      teamId: 'TEAM-003', // Marketing Team got this lead
      createdByPersonId: 'MEM-007', // Sara Al-Fahad from Marketing
      quoteSalesPersonId: 'MEM-001', // Ahmed Al-Salem - Sales
      quotePresalesPersonId: 'MEM-005', // Nora Al-Harbi - Pre-Sales
      salesExecutiveId: 'USR-002',
      presalesId: 'USR-003',
      createdAt: '2024-01-18T14:20:00Z',
      createdBy: 'USR-002',
      notes: 'New opportunity generated by marketing campaign, still in early stages',
      quoteDates: []
    },
    {
      id: 'OPP-003',
      opportunityNumber: 'OPP-2024-003',
      name: 'Data Center Equipment - Global Solutions',
      description: 'Data center upgrade including servers, storage, networking, and cooling systems',
      companyId: 'CUST-003',
      serviceType: 'Security Systems',
      stage: 'negotiation',
      priority: 'critical',
      estimatedValue: 680000,
      targetMargin: 22,
      estimatedCost: 530400,
      currency: 'SAR',
      winProbability: 85,
      requestDate: '2024-01-10',
      teamId: 'TEAM-002', // Pre-Sales Team identified this opportunity
      createdByPersonId: 'MEM-006', // Omar Al-Dosari - Technical Consultant
      quoteSalesPersonId: 'MEM-003', // Mohammed Al-Qahtani - Sales
      quotePresalesPersonId: 'MEM-004', // Khalid Al-Mutairi - Pre-Sales
      salesExecutiveId: 'USR-001',
      presalesId: 'USR-003',
      createdAt: '2024-01-10T09:00:00Z',
      createdBy: 'USR-001',
      notes: 'Very promising deal, client is highly motivated. Final negotiations in progress. Pre-sales team identified opportunity during technical consultation.',
      quoteDates: [
        {
          quoteId: 'QUO-002',
          sentDate: '2024-01-12T00:00:00Z',
          respondedDate: '2024-01-15T00:00:00Z'
        },
        {
          quoteId: 'QUO-003',
          sentDate: '2024-01-22T00:00:00Z'
        }
      ]
    },
    {
      id: 'OPP-004',
      opportunityNumber: 'OPP-2024-004',
      name: 'Annual Maintenance Contract - Tech Corp',
      description: '12-month comprehensive maintenance and support contract',
      companyId: 'CUST-001',
      serviceType: 'Maintenance Services',
      stage: 'closed_won',
      priority: 'low',
      estimatedValue: 120000,
      targetMargin: 30,
      estimatedCost: 84000,
      currency: 'SAR',
      winProbability: 100,
      requestDate: '2023-12-01',
      actualCloseDate: '2024-01-12',
      teamId: 'TEAM-001', // Sales Team - renewal
      createdByPersonId: 'MEM-002', // Fatima Al-Otaibi
      quoteSalesPersonId: 'MEM-002', // Fatima Al-Otaibi - Sales
      quotePresalesPersonId: 'MEM-005', // Nora Al-Harbi - Pre-Sales
      salesExecutiveId: 'USR-002',
      createdAt: '2023-12-01T11:00:00Z',
      createdBy: 'USR-002',
      notes: 'Contract renewed successfully. Sales team handled renewal.',
      quoteDates: [
        {
          quoteId: 'QUO-004',
          sentDate: '2023-12-05T00:00:00Z',
          respondedDate: '2023-12-08T00:00:00Z'
        }
      ]
    }
  ])

  // Computed properties
  const activeOpportunities = computed(() => {
    return opportunities.value.filter(o =>
      o.stage !== 'closed_won' && o.stage !== 'closed_lost'
    )
  })

  const wonOpportunities = computed(() => {
    return opportunities.value.filter(o => o.stage === 'closed_won')
  })

  const lostOpportunities = computed(() => {
    return opportunities.value.filter(o => o.stage === 'closed_lost')
  })

  const totalOpportunityValue = computed(() => {
    return activeOpportunities.value.reduce((sum, o) => sum + o.estimatedValue, 0)
  })

  const totalRevenue = computed(() => {
    return wonOpportunities.value.reduce((sum, o) => sum + o.estimatedValue, 0)
  })

  const winRate = computed(() => {
    const total = wonOpportunities.value.length + lostOpportunities.value.length
    return total > 0 ? (wonOpportunities.value.length / total) * 100 : 0
  })

  const opportunitiesByStage = computed(() => {
    const stages: Record<OpportunityStage, Opportunity[]> = {
      qualification: [],
      proposal: [],
      negotiation: [],
      closed_won: [],
      closed_lost: []
    }

    opportunities.value.forEach(opp => {
      stages[opp.stage].push(opp)
    })

    return stages
  })

  const opportunitiesByPriority = computed(() => {
    const priorities: Record<Priority, Opportunity[]> = {
      low: [],
      medium: [],
      high: [],
      critical: []
    }

    opportunities.value.forEach(opp => {
      priorities[opp.priority].push(opp)
    })

    return priorities
  })

  // Actions
  function addOpportunity(opportunity: Opportunity) {
    opportunities.value.push(opportunity)
  }

  function updateOpportunity(id: string, updates: Partial<Opportunity>) {
    const index = opportunities.value.findIndex(o => o.id === id)
    if (index !== -1) {
      opportunities.value[index] = {
        ...opportunities.value[index],
        ...updates,
        updatedAt: new Date().toISOString()
      }
    }
  }

  function deleteOpportunity(id: string) {
    const index = opportunities.value.findIndex(o => o.id === id)
    if (index !== -1) {
      opportunities.value.splice(index, 1)
    }
  }

  function getOpportunityById(id: string) {
    return opportunities.value.find(o => o.id === id)
  }

  function moveToStage(id: string, stage: OpportunityStage) {
    updateOpportunity(id, { stage })
  }

  function closeAsWon(id: string, actualCloseDate?: string) {
    updateOpportunity(id, {
      stage: 'closed_won',
      actualCloseDate: actualCloseDate || new Date().toISOString().split('T')[0],
      winProbability: 100
    })
  }

  function closeAsLost(id: string, reason: string, competitorName?: string) {
    updateOpportunity(id, {
      stage: 'closed_lost',
      actualCloseDate: new Date().toISOString().split('T')[0],
      winProbability: 0,
      lostReason: reason,
      competitorName
    })
  }

  function getOpportunitiesByCompany(companyId: string) {
    return opportunities.value.filter(o => o.companyId === companyId)
  }

  function getOpportunitiesBySalesExecutive(salesExecutiveId: string) {
    return opportunities.value.filter(o => o.salesExecutiveId === salesExecutiveId)
  }

  // Quote-related functions
  function getQuotesForOpportunity(opportunityId: string) {
    // This will be used by components that import both stores
    // Returns the opportunity for quote linking
    return opportunities.value.find(o => o.id === opportunityId)
  }

  function hasQuotes(opportunityId: string): boolean {
    // This will be checked by components using the quotes store
    // For now, we'll add a computed property in components
    return true // Placeholder - will be determined by quotes store
  }

  return {
    opportunities,
    activeOpportunities,
    wonOpportunities,
    lostOpportunities,
    totalOpportunityValue,
    totalRevenue,
    winRate,
    opportunitiesByStage,
    opportunitiesByPriority,
    addOpportunity,
    updateOpportunity,
    deleteOpportunity,
    getOpportunityById,
    moveToStage,
    closeAsWon,
    closeAsLost,
    getOpportunitiesByCompany,
    getOpportunitiesBySalesExecutive,
    getQuotesForOpportunity,
    hasQuotes
  }
})
